import pandas as pd
import numpy as np
import re
import codecs
import googletrans
from googletrans import Translator
'''
# Loading the dataset for performin filtering opeation of unicode escape sequence
df=pd.read_csv(r'C:\Users\nayan\test_conda\kaggle_competition\data\external\train.csv')
# Identify columns that start with 'Unnamed'
unnamed_columns = [col for col in df.columns if col.startswith('Unnamed')]
# Drop the unwanted columns
df.drop(columns=unnamed_columns, inplace=True)
# Function to detect Unicode escape sequence
def contains_unicode_escape(text):
    if isinstance(text, str):
        unicode_escape_pattern = re.compile(r'\\u[0-9A-Fa-f]{4}')
        return bool(unicode_escape_pattern.search(text))
    return False
# Apply the function to the response_a column
df['contains_unicode_escape'] = df['response_a'].apply(contains_unicode_escape)
# Filter the DataFrame to include only rows where 'column_to_check' is True
filtered_df = df[df['contains_unicode_escape'] == True]
# Get the count of rows with Unicode escape sequences
count = len(filtered_df)
# Save the filtered rows to a CSV file
filtered_df.to_csv('filtered_true_rows.csv', index=False)

# Load the filtered dataset generated by filtering Unicode escape sequences for decoding operation
df = pd.read_csv(r'C:\Users\nayan\test_conda\kaggle_competition\data\interim\filtered_true_rows.csv')
# Drop the 'contains_unicode_sequence' column
df = df.drop(columns='contains_unicode_sequence')
# Define a function to decode Unicode escape sequences
def decode_unicode_escape(text):
    if isinstance(text, str):
        try:
            return text.encode('utf-8', errors='replace').decode('unicode_escape', errors='replace')
        except UnicodeDecodeError:
            return text
    return text
# Apply the function to the relevant columns
df['decoded_prompt'] = df['prompt'].apply(decode_unicode_escape)
df['decoded_response_a'] = df['response_a'].apply(decode_unicode_escape)
df['decoded_response_b'] = df['response_b'].apply(decode_unicode_escape)
columns_to_drop = ['prompt', 'response_a', 'response_b', 'contains_unicode_sequence']
# Drop specified columns
df = df.drop(columns=columns_to_drop)
# New column order
new_column_order = ['id', 'decoded_prompt', 'decoded_response_a', 'decoded_response_b', 'winner_model_a', 'winner_model_b', 'winner_tie']
# Reorder columns
df = df[new_column_order]
# Save to CSV with error handling
df.to_csv('decoded_output_file_v2.csv', index=False, encoding='utf-8-sig')
'''

# third function to transalte all language and formatting to english and here we importing a decoded output file
df = pd.read_csv(r'C:\Users\nayan\test_conda\kaggle_competition\data\interim\decoded_output_file_v2.csv')
# Initialize the translator
translator = Translator()
# Define a function to translate text to English
def translate_to_english(text):
    if isinstance(text, str) and text:  # Ensure the text is a non-empty string
        try:
            print(f"Translating text: {repr(text)[:50]}...")  # Show the input text
            translation = translator.translate(text, dest='en')
            if translation is None or translation.text is None:
                print("Translation returned None.")
                return text
            return translation.text
        except Exception as e:
            print(f"Error translating text: {e}")
            return text
    else:
        print("Invalid text input.")
    return text  # Return the original text if it's None or not a string

# Translate the decoded text to English
df['translated_prompt'] = df['decoded_prompt'].apply(translate_to_english)
df['translated_response_a'] = df['decoded_response_a'].apply(translate_to_english)
df['translated_response_b'] = df['decoded_response_b'].apply(translate_to_english)

# Save to CSV with error handling
df.to_csv('translated_output_file.csv', index=False, encoding='utf-8-sig', errors='replace')