import pandas as pd
import numpy as np
import re
import codecs
import googletrans
from googletrans import Translator

# Loading the dataset for performin filtering opeation of unicode escape sequence
df=pd.read_csv(r'C:\Users\nayan\test_conda\kaggle_competition\data\external\train.csv')
# Identify columns that start with 'Unnamed'
unnamed_columns = [col for col in df.columns if col.startswith('Unnamed')]
# Drop the unwanted columns
df.drop(columns=unnamed_columns, inplace=True)
# Function to detect Unicode escape sequence
def contains_unicode_escape(text):
    if isinstance(text, str):
        unicode_escape_pattern = re.compile(r'\\u[0-9A-Fa-f]{4}')
        return bool(unicode_escape_pattern.search(text))
    return False
# Apply the function to the response_a column
df['contains_unicode_escape'] = df['response_a'].apply(contains_unicode_escape)
# Filter the DataFrame to include only rows where 'column_to_check' is True
filtered_df = df[df['contains_unicode_escape'] == True]
# Get the count of rows with Unicode escape sequences
count = len(filtered_df)
# Save the filtered rows to a CSV file
filtered_df.to_csv('filtered_true_rows.csv', index=False)

# Load the filtered dataset generated by filtering Unicode escape sequences for decoding operation
df = pd.read_csv(r'C:\Users\nayan\test_conda\kaggle_competition\data\interim\filtered_true_rows.csv')
# Drop the 'contains_unicode_sequence' column
df = df.drop(columns='contains_unicode_sequence')
# Define a function to decode Unicode escape sequences
def decode_unicode_escape(text):
    if isinstance(text, str):
        try:
            return text.encode('utf-8', errors='replace').decode('unicode_escape', errors='replace')
        except UnicodeDecodeError:
            return text
    return text
# Apply the function to the relevant columns
df['decoded_prompt'] = df['prompt'].apply(decode_unicode_escape)
df['decoded_response_a'] = df['response_a'].apply(decode_unicode_escape)
df['decoded_response_b'] = df['response_b'].apply(decode_unicode_escape)
columns_to_drop = ['prompt', 'response_a', 'response_b', 'contains_unicode_sequence']
# Drop specified columns
df = df.drop(columns=columns_to_drop)
# New column order
new_column_order = ['id', 'decoded_prompt', 'decoded_response_a', 'decoded_response_b', 'winner_model_a', 'winner_model_b', 'winner_tie']
# Reorder columns
df = df[new_column_order]
# Save to CSV with error handling
df.to_csv('decoded_output_file_v2.csv', index=False, encoding='utf-8-sig')

# Third function to transalte all language and formatting to english and here we importing a decoded output file
# So actually this is the third step but unfortunately we have to create a new .ipynb file for trnsalting task because the task itself is very big. but now we have to consider this code snippet as this function and do the opeation forward.
pip install googletrans==3.1.0a0
# third function to transalte all language and formatting to english and here we importing a decoded output file
df = pd.read_csv(r'/content/drive/MyDrive/ArmoRM - LMSYS/decoded_output_file_v2.csv')
# Define the batch size
batch_size = 1000
# Calculate the number of batches
num_batches = np.ceil(len(df) / batch_size).astype(int)
# Initialize the translator
translator = Translator()
# Define a function to translate text to English
def translate_to_english(text):
    if isinstance(text, str) and text:  # Ensure the text is a non-empty string
        try:
            print(f"Translating text: {repr(text)[:50]}...")  # Show the input text
            translation = translator.translate(text, dest='en')
            if translation is None or translation.text is None:
                print("Translation returned None.")
                return text
            return translation.text
        except Exception as e:
            print(f"Error translating text: {e}")
            return text
    else:
        print("Invalid text input.")
    return text  # Return the original text if it's None or not a string
# Loop through each batch
for i in range(num_batches):
    # Define the start and end index for this batch
    start_idx = i * batch_size
    end_idx = min((i + 1) * batch_size, len(df))
    # Select the batch
    batch_df = df.iloc[start_idx:end_idx].copy()
    # Perform the translation on the batch
    batch_df['translated_prompt'] = batch_df['decoded_prompt'].apply(translate_to_english)
    batch_df['translated_response_a'] = batch_df['decoded_response_a'].apply(translate_to_english)
    batch_df['translated_response_b'] = batch_df['decoded_response_b'].apply(translate_to_english)
    # Save the translated batch to a CSV file
    batch_df.to_csv(f'translated_batch_{i+1}.csv', index=False, encoding='utf-8-sig')
    # Optionally, you can print a status update
    print(f"Batch {i+1}/{num_batches} processed and saved.")
import pandas as pd

# List of paths to your batch files
batch_files = [
    '/content/drive/MyDrive/ArmoRM - LMSYS/translated_batch/translated_batch_1.csv',
    '/content/drive/MyDrive/ArmoRM - LMSYS/translated_batch/translated_batch_1.csv',
    '/content/drive/MyDrive/ArmoRM - LMSYS/translated_batch/translated_batch_1.csv',
    '/content/drive/MyDrive/ArmoRM - LMSYS/translated_batch/translated_batch_1.csv',
    '/content/drive/MyDrive/ArmoRM - LMSYS/translated_batch/translated_batch_1.csv',
    '/content/drive/MyDrive/ArmoRM - LMSYS/translated_batch/translated_batch_1.csv',
    '/content/drive/MyDrive/ArmoRM - LMSYS/translated_batch/translated_batch_1.csv',
    '/content/drive/MyDrive/ArmoRM - LMSYS/translated_batch/translated_batch_1.csv',
    # Add more paths as needed
]
# Combine them into a single DataFrame
translated_df = pd.concat([pd.read_csv(f) for f in batch_files], ignore_index=True)
# Save the combined DataFrame to a CSV file
translated_df.to_csv('/content/drive/MyDrive/ArmoRM - LMSYS/translated_batch/translated_output.csv', index=False, encoding='utf-8-sig')
# Remove columns 'B' and 'D'
translated_df = translated_df.drop(columns=['decoded_prompt', 'decoded_response_a', 'decoded_response_b'])
# Reorder the remaining columns to ['E', 'C', 'A']
translated_df = translated_df[['id', 'model_a', 'model_b', 'translated_prompt', 'translated_response_a', 'translated_response_b', 'winner_model_a', 'winner_model_b', 'winner_tie']]
translated_df.to_csv('/content/drive/MyDrive/ArmoRM - LMSYS/translated_batch/translated_output_1.csv', index=False, encoding='utf-8-sig')

# Here in this code snippet we're performing the opertion to identify the unicode escape sequence and delete the UES rows and then merge with transalted 
# Loading the dataset for performin filtering opeation of unicode escape sequence
df=pd.read_csv(r'C:\Users\nayan\test_conda\kaggle_competition\data\external\train.csv')
# Function to detect Unicode escape sequence
def contains_unicode_escape(text):
    if isinstance(text, str):
        unicode_escape_pattern = re.compile(r'\\u[0-9A-Fa-f]{4}')
        return bool(unicode_escape_pattern.search(text))
    return False
# Apply the function to the response_a column
df['contains_unicode_escape'] = df['response_a'].apply(contains_unicode_escape)
# Filter the DataFrame to include only rows where 'column_to_check' is True
filtered_df = df[df['contains_unicode_escape'] == False]
# Get the count of rows with Unicode escape sequences
count = len(filtered_df)
# Save the filtered rows to a CSV file
filtered_df.to_csv('train_csv_dataset_notContain_UES.csv', index=False)
#merging opertion
df1 = pd.read_csv(r'C:\Users\nayan\test_conda\kaggle_competition\data\interim\train_csv_dataset_notContain_UES.csv')
# Drop specified columns
df1 = df1.drop(columns='contains_unicode_escape')
df2 = pd.read_csv(r'C:\Users\nayan\test_conda\kaggle_competition\data\interim\translated_output_1.csv')
# Rename columns
df2.rename(columns={
    'translated_prompt': 'prompt',
    'translated_response_a': 'response_a',
    'translated_response_b': 'response_b'
}, inplace=True)
# Convert float values to integers
df2['winner_model_a'] = df2['winner_model_a'].astype(int)
df2['winner_model_b'] = df2['winner_model_b'].astype(int)
df2['winner_tie'] = df2['winner_tie'].astype(int)
# Concatenate df1 and df2
combined_df = pd.concat([df1, df2])
# Sort by the 'id' column to restore original order
sorted_df = combined_df.sort_values(by='id').reset_index(drop=True)
