import pandas as pd
import numpy as np
import re
import codecs
import googletrans
from googletrans import Translator

# Loading the dataset for performin filtering opeation of unicode escape sequence
df=pd.read_csv(r'C:\Users\nayan\test_conda\kaggle_competition\data\external\train.csv')
# Identify columns that start with 'Unnamed'
unnamed_columns = [col for col in df.columns if col.startswith('Unnamed')]
# Drop the unwanted columns
df.drop(columns=unnamed_columns, inplace=True)
# Function to detect Unicode escape sequence
def contains_unicode_escape(text):
    if isinstance(text, str):
        unicode_escape_pattern = re.compile(r'\\u[0-9A-Fa-f]{4}')
        return bool(unicode_escape_pattern.search(text))
    return False
# Apply the function to the response_a column
df['contains_unicode_escape'] = df['response_a'].apply(contains_unicode_escape)
# Filter the DataFrame to include only rows where 'column_to_check' is True
filtered_df = df[df['contains_unicode_escape'] == True]
# Get the count of rows with Unicode escape sequences
count = len(filtered_df)
# Save the filtered rows to a CSV file
filtered_df.to_csv('filtered_true_rows.csv', index=False)

# Load the filtered dataset generated by filtering Unicode escape sequences for decoding operation
df = pd.read_csv(r'C:\Users\nayan\test_conda\kaggle_competition\data\interim\filtered_true_rows.csv')
# Drop the 'contains_unicode_sequence' column
df = df.drop(columns='contains_unicode_sequence')
# Define a function to decode Unicode escape sequences
def decode_unicode_escape(text):
    if isinstance(text, str):
        try:
            return text.encode('utf-8', errors='replace').decode('unicode_escape', errors='replace')
        except UnicodeDecodeError:
            return text
    return text
# Apply the function to the relevant columns
df['decoded_prompt'] = df['prompt'].apply(decode_unicode_escape)
df['decoded_response_a'] = df['response_a'].apply(decode_unicode_escape)
df['decoded_response_b'] = df['response_b'].apply(decode_unicode_escape)
columns_to_drop = ['prompt', 'response_a', 'response_b', 'contains_unicode_sequence']
# Drop specified columns
df = df.drop(columns=columns_to_drop)
# New column order
new_column_order = ['id', 'decoded_prompt', 'decoded_response_a', 'decoded_response_b', 'winner_model_a', 'winner_model_b', 'winner_tie']
# Reorder columns
df = df[new_column_order]
# Save to CSV with error handling
df.to_csv('decoded_output_file_v2.csv', index=False, encoding='utf-8-sig')

# Third function to transalte all language and formatting to english and here we importing a decoded output file
# So actually this is the third step but unfortunately we have to create a new .ipynb file for trnsalting task because the task itself is very big. but now we have to consider this code snippet as this function and do the opeation forward.

# Here in this code snippet we're performing the opertion to identify the unicode escape sequence and delete the UES rows and then merge with transalted 
# Loading the dataset for performin filtering opeation of unicode escape sequence
df=pd.read_csv(r'C:\Users\nayan\test_conda\kaggle_competition\data\external\train.csv')
# Function to detect Unicode escape sequence
def contains_unicode_escape(text):
    if isinstance(text, str):
        unicode_escape_pattern = re.compile(r'\\u[0-9A-Fa-f]{4}')
        return bool(unicode_escape_pattern.search(text))
    return False
# Apply the function to the response_a column
df['contains_unicode_escape'] = df['response_a'].apply(contains_unicode_escape)
# Filter the DataFrame to include only rows where 'column_to_check' is True
filtered_df = df[df['contains_unicode_escape'] == False]
# Get the count of rows with Unicode escape sequences
count = len(filtered_df)
# Save the filtered rows to a CSV file
filtered_df.to_csv('train_csv_dataset_notContain_UES.csv', index=False)
#merging opertion
df1 = pd.read_csv(r'C:\Users\nayan\test_conda\kaggle_competition\data\interim\train_csv_dataset_notContain_UES.csv')
# Drop specified columns
df1 = df1.drop(columns='contains_unicode_escape')
df2 = pd.read_csv(r'C:\Users\nayan\test_conda\kaggle_competition\data\interim\translated_output_1.csv')
# Rename columns
df2.rename(columns={
    'translated_prompt': 'prompt',
    'translated_response_a': 'response_a',
    'translated_response_b': 'response_b'
}, inplace=True)
# Convert float values to integers
df2['winner_model_a'] = df2['winner_model_a'].astype(int)
df2['winner_model_b'] = df2['winner_model_b'].astype(int)
df2['winner_tie'] = df2['winner_tie'].astype(int)
# Concatenate df1 and df2
combined_df = pd.concat([df1, df2])
# Sort by the 'id' column to restore original order
sorted_df = combined_df.sort_values(by='id').reset_index(drop=True)
